blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/mondaycom/vibe/discussions
    about: Suggest new features
  - name: Questions & Discussions
    url: https://github.com/mondaycom/vibe/discussions
    about: Use GitHub discussions for questions and suggestions
